[workspace]
members=["crates/*"]
resolver="2"

[profile.wasm]
opt-level="s"
lto="thin"
codegen-units=1
panic="abort"
inherits="release"

[workspace.package]
version="0.3.0"
edition="2021"
license="MIT OR Apache-2.0"
authors=["Henry Gressmann <mail@henrygressmann.de>"]
repository="https://github.com/explodingcamera/tinywasm"

[package]
name="tinywasm-root"
publish=false
edition="2021"

[[example]]
name="wasm-rust"
test=false

[[bench]]
name="selfhosted"
harness=false

[[bench]]
name="fibonacci"
harness=false


[[bench]]
name="argon2id"
harness=false

[profile.bench]
opt-level=3
lto="thin"
codegen-units=1
debug=true

[dev-dependencies]
color-eyre="0.6"
criterion={version="0.5", features=["html_reports"]}

tinywasm={path="crates/tinywasm", features=["unsafe"]}
wat={version="1.0"}
wasmi={version="0.31", features=["std"]}
wasmer={version="4.2", features=["cranelift", "singlepass"]}
wasmtime={version="17.0", features=["cranelift"]}
argon2={version="0.5"}
