[workspace]
members=["crates/*", "examples/rust"]
resolver="2"

[profile.wasm]
opt-level="z"
lto="thin"
codegen-units=1
panic="abort"
inherits="release"

[workspace.package]
version="0.3.0-alpha.0"
edition="2021"
license="MIT OR Apache-2.0"
authors=["Henry Gressmann <mail@henrygressmann.de>"]
repository="https://github.com/explodingcamera/tinywasm"

[package]
name="tinywasm-root"
publish=false
edition="2021"

[dev-dependencies]
color-eyre="0.6"
tinywasm={path="crates/tinywasm"}
