[workspace]
members=["crates/*"]
default-members=["crates/cli"]
resolver="2"

[workspace.package]
version="0.3.0-alpha.0"
edition="2021"
license="MIT OR Apache-2.0"
authors=["Henry Gressmann <mail@henrygressmann.de>"]
repository="https://github.com/explodingcamera/tinywasm"
