[package]
name="tinywasm-cli"
version="0.0.0"
edition="2021"

[[bin]]
name="tinywasm"
path="bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinywasm={path="../tinywasm"}
argh="0.1"
color-eyre="0.6"
tracing="0.1"
tracing-subscriber="0.3"
