[package]
name="tinywasm-cli"
version="0.0.0"
edition="2021"
publish=false

[[bin]]
name="tinywasm-cli"
path="src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinywasm={path="../tinywasm", features=["std", "parser"]}
argh="0.1"
color-eyre={version="0.6", default-features=false}
log="0.4"
pretty_env_logger="0.5"
wast={version="69.0", optional=true}

[features]
default=["wat"]
wat=["dep:wast"]
