[package]
name="tinywasm-parser"
version="0.0.3"
description="TinyWasm parser"
edition.workspace=true
license.workspace=true
authors.workspace=true
repository.workspace=true

[dependencies]
# fork of wasmparser with no_std support, see https://github.com/bytecodealliance/wasmtime/issues/3495
# TODO: create dependency free parser
wasmparser={version="0.100", package="wasmparser-nostd", default-features=false}
log={version="0.4", optional=true}
tinywasm-types={version="0.0.3", path="../types"}

[features]
default=["std", "logging"]
logging=["log"]
std=[]
