[package]
name="tinywasm"
version="0.0.3"
description="A tiny WebAssembly interpreter"
edition.workspace=true
license.workspace=true
authors.workspace=true
repository.workspace=true
readme="../../README.md"

[lib]
name="tinywasm"
path="src/lib.rs"

[dependencies]
log={version="0.4", optional=true}
tinywasm-parser={version="0.0.3", path="../parser", default-features=false, optional=true}
tinywasm-types={version="0.0.3", path="../types", default-features=false}

[features]
default=["std", "parser", "logging"]
logging=["log", "tinywasm-types/logging", "tinywasm-parser?/logging"]
std=["tinywasm-parser?/std", "tinywasm-types/std"]
parser=["tinywasm-parser"]
nightly=[]
