[package]
name="tinywasm"
version="0.0.0"
edition="2021"

[lib]
name="tinywasm"
path="src/lib.rs"

[dependencies]
log={version="0.4", optional=true}
tinywasm-parser={path="../parser", default-features=false, optional=true}
tinywasm-types={path="../types", default-features=false}

[features]
default=["std", "parser", "logging"]
logging=["log", "tinywasm-types/logging", "tinywasm-parser?/logging"]
std=["tinywasm-parser?/std", "tinywasm-types/std"]
parser=["tinywasm-parser"]
