[package]
name="tinywasm"
version="0.0.0"
edition="2021"

[lib]
path="src/lib.rs"

[dependencies]
thiserror={version="1.0", package="thiserror-core", default-features=false}
wasmparser={version="0.100", package="wasmparser-nostd", default-features=false}
tracing={version="0.1.38", default-features=false} # logging
hashbrown="0.14"

[features]
default=["std"]
std=["thiserror/std"]
