[package]
name="tinywasm"
version="0.0.0"
edition="2021"

[lib]
name="tinywasm"
path="src/lib.rs"
crate-type=["cdylib", "rlib"]

[dependencies]
log="0.4"
tinywasm-parser={path="../parser", default-features=false}
tinywasm-types={path="../types", default-features=false}

wasmparser={version="0.100", package="wasmparser-nostd", default-features=false}

[features]
default=["std"]
std=["tinywasm-parser/std", "tinywasm-types/std"]
