[package]
name="tinywasm"
version="0.0.0"
edition="2021"

[lib]
path="src/lib.rs"

[dependencies]
# fork of wasmparser with no_std support, see https://github.com/bytecodealliance/wasmtime/issues/3495
# TODO: create dependency free parser
wasmparser={version="0.100", package="wasmparser-nostd", default-features=false}
tracing={version="0.1.38", default-features=false} # logging

[features]
default=["std"]
std=[]
