[package]
name="tinywasm"
version="0.0.0"
edition="2021"

[lib]
path="src/lib.rs"

[dependencies]
tracing={version="0.1.38", default-features=false} # logging
tinywasm-parser={path="../parser"}
tinywasm-types={path="../types"}

wasmparser={version="0.100", package="wasmparser-nostd", default-features=false}

[features]
default=["std"]
std=[]
