[package]
name="tinywasm-types"
version="0.0.0"
edition="2021"

[dependencies]
log={version="0.4", optional=true}
rkyv={version="0.7", optional=true, default-features=false}

[features]
default=["std"]
std=[]
serialize=["dep:rkyv", "dep:log"]
