[package]
name="tinywasm-types"
version="0.0.0"
edition="2021"

[dependencies]
log="0.4.20"
rkyv={version="0.7", optional=true, default-features=false}

[features]
default=["std"]
std=[]
serialize=["dep:rkyv"]
