[package]
name="tinywasm-types"
version="0.0.0"
edition="2021"

[dependencies]
tracing={version="0.1.38", default-features=false} # logging
rkyv={version="0.7", optional=true, default-features=false}

[features]
default=["std"]
std=[]
serialize=["dep:rkyv"]
