[package]
name="tinywasm-types"
version="0.0.3"
description="TinyWasm types"
edition.workspace=true
license.workspace=true
authors.workspace=true
repository.workspace=true

[dependencies]
log={version="0.4", optional=true}
rkyv={version="0.7", optional=true, default-features=false, features=["size_32"]}

[features]
default=["std", "logging"]
std=["rkyv/std"]
serialize=["dep:rkyv", "dep:log"]
logging=["dep:log"]
