cargo-features=["per-package-target"]

[package]
publish=false
name="rust-wasm-examples"
forced-target="wasm32-unknown-unknown"
edition="2021"

[dependencies]
tinywasm={path="../../crates/tinywasm", features=["parser", "std"]}

[[bin]]
name="hello"
path="src/hello.rs"

[[bin]]
name="tinywasm"
path="src/tinywasm.rs"
