name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-std:
    name: Test with default features on stable Rust
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install stable Rust toolchain & Binaryen
        run: |
          rustup update stable
          rustup update nightly
          sudo apt-get install -y binaryen

      - name: Build wasm
        run: ./examples/rust/build.sh

      - name: Build (stable)
        run: cargo +stable build --workspace

      - name: Run tests (stable)
        run: cargo +stable test --workspace

      - name: Run MVP testsuite
        run: cargo +stable test-mvp

  test-no-std:
    name: Test without default features on nightly Rust
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install nightly Rust toolchain & Binaryen
        run: |
          rustup update nightly
          sudo apt-get install -y binaryen

      - name: Build wasm
        run: ./examples/rust/build.sh

      - name: Build (nightly, no default features)
        run: cargo +nightly build --workspace --no-default-features

      - name: Run tests (nightly, no default features)
        run: cargo +nightly test --workspace --no-default-features

      - name: Run MVP testsuite (nightly)
        run: cargo +nightly test-mvp
