name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-std:
    name: Test with default features on stable Rust
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install stable Rust toolchain
        run: |
          rustup toolchain install stable
          rustup default stable

      - name: Build (stable)
        run: cargo +stable build --workspace --exclude wasm-testsuite

      - name: Run tests (stable)
        run: cargo +stable test --workspace --exclude wasm-testsuite

  test-no-std:
    name: Test without default features on nightly Rust
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install nightly Rust toolchain
        run: |
          rustup toolchain install nightly
          rustup default nightly

      - name: Build (nightly, no default features)
        run: cargo +nightly build --workspace --exclude wasm-testsuite --no-default-features

      - name: Run tests (nightly, no default features)
        run: cargo +nightly test --workspace --exclude wasm-testsuite --no-default-features
